kind: Pod
apiVersion: v1
metadata:
  name: mon-premier-pod
spec:
  containers:
  - name: container-1
    image: sdenel/hello-world # TODO use nginx:alpine  instead during the TP instead of sdenel/hello-world
